# Generated by Django 3.0.5 on 2020-04-29 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_pizza_toppings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dinnerplatter',
            old_name='option',
            new_name='filling',
        ),
    ]
