# Generated by Django 3.0.5 on 2020-04-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200429_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='DinnerFilling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SaladFilling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='Topping',
            new_name='PizzaTopping',
        ),
        migrations.RemoveField(
            model_name='dinnerplatter',
            name='filling',
        ),
        migrations.RemoveField(
            model_name='pasta',
            name='filling',
        ),
        migrations.AddField(
            model_name='pasta',
            name='filling',
            field=models.ManyToManyField(blank=True, to='orders.PastaFilling'),
        ),
        migrations.RemoveField(
            model_name='salad',
            name='filling',
        ),
        migrations.AddField(
            model_name='dinnerplatter',
            name='filling',
            field=models.ManyToManyField(blank=True, to='orders.DinnerFilling'),
        ),
        migrations.AddField(
            model_name='salad',
            name='filling',
            field=models.ManyToManyField(blank=True, to='orders.SaladFilling'),
        ),
    ]
