# Generated by Django 3.0.5 on 2020-04-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200429_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinnerfilling',
            name='filling',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dinnerfilling',
            name='priceLarge',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dinnerfilling',
            name='priceSmall',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pastafilling',
            name='filling',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pastafilling',
            name='priceLarge',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pastafilling',
            name='priceSmall',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saladfilling',
            name='filling',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saladfilling',
            name='priceLarge',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saladfilling',
            name='priceSmall',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
