# Generated by Django 3.0.5 on 2020-04-29 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20200429_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pastafilling',
            old_name='priceLarge',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='pastafilling',
            name='priceSmall',
        ),
    ]
