# Generated by Django 3.0.5 on 2020-04-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20200429_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='RegularPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('priceSmall', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('priceLarge', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SicilianPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('priceSmall', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('priceLarge', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='toppings',
        ),
        migrations.RemoveField(
            model_name='dinnerplatter',
            name='size',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='size',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='xtra_cheese',
        ),
        migrations.AddField(
            model_name='dinnerplatter',
            name='priceLarge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='dinnerplatter',
            name='priceSmall',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='pasta',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='salad',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='sub',
            name='priceLarge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='sub',
            name='priceSmall',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.RemoveField(
            model_name='dinnerplatter',
            name='filling',
        ),
        migrations.AddField(
            model_name='dinnerplatter',
            name='filling',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='pasta',
            name='filling',
        ),
        migrations.AddField(
            model_name='pasta',
            name='filling',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='salad',
            name='filling',
        ),
        migrations.AddField(
            model_name='salad',
            name='filling',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='sub',
            name='filling',
        ),
        migrations.AddField(
            model_name='sub',
            name='filling',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DinnerFilling',
        ),
        migrations.DeleteModel(
            name='PastaFilling',
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.DeleteModel(
            name='SaladFilling',
        ),
        migrations.DeleteModel(
            name='SubFilling',
        ),
    ]
