# Generated by Django 3.0.5 on 2020-05-01 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200430_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dinnerplatter',
            old_name='filling',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='pasta',
            old_name='filling',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='salad',
            old_name='filling',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sub',
            old_name='filling',
            new_name='name',
        ),
    ]
