# Generated by Django 3.0.5 on 2020-04-29 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20200429_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dinnerplatter',
            old_name='size',
            new_name='large',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='size',
            new_name='large',
        ),
        migrations.RenameField(
            model_name='sub',
            old_name='size',
            new_name='large',
        ),
    ]
