# Generated by Django 3.0.5 on 2020-05-01 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20200430_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pasta',
            old_name='price',
            new_name='priceLarge',
        ),
        migrations.RenameField(
            model_name='pizzatopping',
            old_name='topping',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='salad',
            old_name='price',
            new_name='priceLarge',
        ),
    ]
